### ISSUE TITLE
Move IJabbrRepository and InMemoryRepository over to Jabbr-Core to get chatroom functionality

### ISSUE THREAD

**Issue by heatherbshapiro** [MachUpskillingFY17/JabbR-Core#49] opened 2016-09-06 20:02 UTC
Move IJabbrRepository and InMemoryRepository over to Jabbr-Core.Data and get EF working with Basic chatroom functionality. #41

**Comment by KSLHacks** [comment] 2016-09-07 19:36
Successfully marged PR #50 into Dev. Crated new branch from dev --> KSLHacks/moveRepositories.

**Comment by heatherbshapiro** [comment] 2016-09-08 02:56
I moved our fake data into inMemory repository in the latest commit to KSLHacks/moveRepositories. Having difficulties with naming conventions to actually get the data through. Right now I get these errorr when they weren't there before:
`jquery-2.0.3.min.js:6 POST http://localhost:59395/signalr/send?transport=serverSentEvents&clientProtoc…i8%2FN9j2UBfDKN00Tk6JaU&connectionData=%5B%7B%22name%22%3A%22chat%22%7D%5D 500 (Internal Server Error)send @ jquery-2.0.3.min.js:6ajax @ jquery-2.0.3.min.js:6ajax @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8ajaxSend @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8send @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8send @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8invoke @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8join @ hubs:97(anonymous function) @ Chat.js:1322l @ jquery-2.0.3.min.js:4fireWith @ jquery-2.0.3.min.js:4i.(anonymous function) @ jquery-2.0.3.min.js:4(anonymous function) @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8dispatch @ jquery-2.0.3.min.js:5y.handle @ jquery-2.0.3.min.js:5trigger @ jquery-2.0.3.min.js:5e.event.trigger @ jquery-migrate-1.2.1.min.js:2triggerHandler @ jquery-2.0.3.min.js:5(anonymous function) @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8success @ jquery.signalR-2.2.0-pre-140709-b104.min.js:8l @ jquery-2.0.3.min.js:4fireWith @ jquery-2.0.3.min.js:4k @ jquery-2.0.3.min.js:6(anonymous function) @ jquery-2.0.3.min.js:6`

`jquery.signalR-2.2.0-pre-140709-b104.min.js:8` [22:53:40 GMT-0400 (Eastern Daylight Time)] SignalR: chat.Join failed to execute. Error: Error: Send failed`

**Comment by KSLHacks** [comment] 2016-09-08 05:29
The issue is caused by passing InMemory repository as a parameter for the chat() constructor. -->
[ InvalidOperationException: Unable to resolve service for type 'JabbR_Core.Services.InMemoryRepository' while attempting to activate 'JabbR_Core.Hubs.Chat'. ]
```
public Chat(
            InMemoryRepository repository,
            )
```
**Workaround:** Initialize the InMemoryRepository() object inside the chat() constructor. This still allows us to assign the private readonly properties to InMemoryRepository()'s properties which are already initialized and populated with mock data. We can use this approach until we can pass in as a param.
```
private readonly InMemoryRepository _repository;
        private readonly List<LobbyRoomViewModel> _lobbyRoomList;
        private readonly LobbyRoomViewModel _lobbyRoom;
        private readonly List<ChatRoom> _roomList;
        private readonly ChatUser _user;
        private readonly List<string> _chatRooms;
        private readonly ILogger _logger;
        private readonly IChatService _service;


        public Chat(
            //InMemoryRepository repository,
            //ILogger logger,
            //IChatService service
            )
        {
            _repository = new InMemoryRepository();
            //_repository = repository;
            _roomList = _repository.RoomList;
            _lobbyRoom = _repository.LobbyRoomView;
            _lobbyRoomList = _repository.LobbyRoomList;
            _user = _repository.User;
            //_chatRooms = repository.ChatRooms;
            //_logger = logger;
            //_service = service;

        }
```

**Comment by KSLHacks** [comment] 2016-09-08 05:32
Bringing over many Models and Infrastructure classes to Jabbr-Core so we can keep Chat.cs as close as possible to Jabbr.

**Comment by KSLHacks** [comment] 2016-09-08 23:03
Isolated open room click bind event to Chat.js .. bind event calls '/join' command.

```
$ui.bind(ui.events.openRoom, function (ev, room) {
        try {
            chat.server.send('/join ' + room, chat.state.activeRoom)
                    .fail(function (e) {
                        ui.setActiveRoom('Lobby');
                        if (e.source === 'HubException') {
                            ui.addErrorToActiveRoom(e.message);
                        }
                    });
            }
            catch (e) {
                connection.hub.log('openRoom failed -- KSL was here');
            }
    });
```

**Comment by heatherbshapiro** [comment] 2016-09-09 03:30
Based on the old Jabbr logs, these are the functions we need to get working in order for the UI to work. Right now we have "Invoking/ed chat.send" . I am working on the joinRoom event. The old jabbr uses INotificationServices, which implements a lot more than we need at this time and will be a hassle to move everything over, so will try to find a workaround for now.

`
[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: Invoking chat.Send

[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: Triggering client hub event 'joinRoom' on hub 'Chat'.
[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: getRoomInfo(franz)
[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: Invoking chat.GetRoomInfo
[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: Triggering client hub event 'updateRoom' on hub 'Chat'.
[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: Invoked chat.Send
[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: Invoked chat.GetRoomInfo
[23:26:41 GMT-0400 (Eastern Daylight Time)] SignalR: getRoomInfo.done(franz)`

**Comment by heatherbshapiro** [comment] 2016-09-09 04:34
I was able to get joinRoom to be triggered by adding Clients.Caller.joinRoom(user, room, new object[0]); to chat.send in chat.cs. It now has a loading screen that is trying to call getRoomInfo. It only works though if you click it twice, which i'm not sure why. I'm not very comfortable with the location of it, but for now it works. 

I tried to move over GetRoomInfo but it depends a lot on the repository so the pull request right now does not include that.

**Comment by adamtuliper** [comment] 2016-09-09 08:07
@heatherbshapiro whats the location you don't like? What is normally passed in place of the new object[0]? Does getRoomInfo work?

**Comment by KSLHacks** [comment] 2016-09-09 22:26
Update: No visible progress past the loading screen upon click to enter room event. Brought over the INotificationServices as well as some classes in the Commands folder. Still stepping through callstack.

Some issues implementing commands: Managed Extensibility Framework (MEF) [inheritedExport] not supported in Core. Possible work around using Microsoft.Reflection.

**Comment by adamtuliper** [comment] 2016-09-09 23:10
any luck in the workaround I sent with GetCommands?

**Comment by KSLHacks** [comment] 2016-09-20 18:35
@adamtuliper We were able to use it and populate the joinCommand :)

**Comment by KSLHacks** [comment] 2016-09-22 17:42
Merged adamt/loginstub into Heather-Kevin/chatroom. @adamtuliper 's middleware will help remove the need for mock data throughout the project while implementing a basic user cookie with id and name.

**Comment by JamesEarle** [comment] 2016-09-29 20:39
This is completed. There are still functional things that need updating, but this issue is stale and more recent issues have been added that are more representative of the current state of this task.

**Closed by JamesEarle** 2016-09-29 20:39 UTC
Labels: 3 - Done, assigned to uber, bug
